### ISSUE TITLE
error on load up(1.14.4) fabric - extrapieces-2.4.2.jar

### ISSUE THREAD

**Issue by SDUBZ** [Shnupbups/extra-pieces#24]
Exception in thread "main" java.lang.RuntimeException: Failed to resolve mods!
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:147)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:120)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Caused by: net.fabricmc.loader.discovery.ModResolutionException: Could not resolve valid mod collection (at: extrapieces breaks {tweed @ [*]})
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:206)
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:508)
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:145)
	... 2 more
Caused by: net.fabricmc.loader.util.sat4j.specs.ContradictionException: Creating Empty clause ?
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.propagationCheck(Clauses.java:117)
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.sanityCheck(Clauses.java:97)
	at net.fabricmc.loader.util.sat4j.minisat.constraints.MixedDataStructureDanielWL.createClause(MixedDataStructureDanielWL.java:81)
	at net.fabricmc.loader.util.sat4j.minisat.core.Solver.addClause(Solver.java:401)
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:203)
	... 4 more

Full log : 
[latest.log](https://github.com/Shnupbups/extra-pieces/files/3438226/latest.log)

**Comment by Shnupbups** [comment]
Extra Pieces is incompatible with Tweed.
