### ISSUE TITLE
Can't explain this on loading game...

### ISSUE THREAD

**Issue by Snowfalldevice** [Shnupbups/extra-pieces#34]
[22:09:56] [main/INFO]: [STDERR]: blue.endless.jankson.impl.SyntaxError: Expected to find '}' to end an object, found EOF instead.
[22:09:56] [main/INFO]: [STDERR]: 	at blue.endless.jankson.impl.ObjectParserContext.eof(ObjectParserContext.java:135)
[22:09:56] [main/INFO]: [STDERR]: 	at blue.endless.jankson.Jankson.load(Jankson.java:171)
[22:09:56] [main/INFO]: [STDERR]: 	at blue.endless.jankson.Jankson.load(Jankson.java:77)
[22:09:56] [main/INFO]: [STDERR]: 	at com.shnupbups.extrapieces.register.ModConfigs.isDefaultPackOutdated(ModConfigs.java:323)
[22:09:56] [main/INFO]: [STDERR]: 	at com.shnupbups.extrapieces.register.ModConfigs.initPiecePacks(ModConfigs.java:146)
[22:09:56] [main/INFO]: [STDERR]: 	at com.shnupbups.extrapieces.ExtraPieces.onInitialize(ExtraPieces.java:96)
[22:09:56] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient$$Lambda$1557/869085647.accept(Unknown Source)
[22:09:56] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.lambda$logErrors$0(EntrypointUtils.java:38)
[22:09:56] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils$$Lambda$1558/615271668.accept(Unknown Source)
[22:09:56] [main/INFO]: [STDERR]: 	at java.util.ArrayList.forEach(Unknown Source)
[22:09:56] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.logErrors(EntrypointUtils.java:36)
[22:09:56] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
[22:09:56] [main/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1503(class_310.java)
[22:09:56] [main/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1514(class_310.java:394)
[22:09:56] [main/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:155)
[22:09:56] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[22:09:56] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[22:09:56] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[22:09:56] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[22:09:56] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:178)
[22:09:56] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:131)
[22:09:56] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
[22:09:56] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[22:09:56] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[22:09:56] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[22:09:56] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[22:09:56] [main/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
[22:09:56] [main/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
[22:09:56] [main/INFO]: [STDERR]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[22:09:56] [main/INFO]: [STDERR]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)

**Comment by Shnupbups** [comment]
Have you edited the default piece pack? The error should only happen when the pack's JSON is invalid.
